---
extends: standard
rules:
  semi: 0
  no-extra-semi: 0
  brace-style: [2, stroustrup]
  space-before-function-paren: [error, never]

plugins:
  - standard

parserOptions:
  sourceType: module
  ecmaFeatures:
    modules: true

env:
  amd: true
  browser: true
  es6: true
  jquery: true
  node: true
