export const DEFAULTS = {
  CADENCE: {
    ERASE: [40, 80],
    AFTER_WRITE: [120, 160],
  },
}

export const ELEMENT_TYPES = {
  TEXT: 'TEXT',
  HTML: 'HTML',
}

export const EVENTS = {
  WRITE_CHARACTERS: 'WRITE_CHARACTERS',
  ERASE_LAST_CHARACTER: 'ERASE_LAST_CHARACTER',
  ERASE_CHARACTER: 'ERASE_CHARACTER',
  WAIT: 'WAIT',
}
