export const ELEMENT_TYPES = {
  TEXT: 'TEXT',
  HTML: 'HTML',
}

export const EVENTS = {
  WRITE: 'WRITE',
  WRITE_HTML: 'WRITE_HTML',
  ERASE_LAST_CHARACTER: 'ERASE_LAST_CHARACTER',
  ERASE_CHARACTER: 'ERASE_CHARACTER',
  ERASE_CHARACTERS: 'ERASE_CHARACTERS',
  WAIT: 'WAIT',
}

export const DEFAULTS = {
  CADENCE: {
    WRITE_CHARACTER: [40, 80],
    ERASE_CHARACTER: [60, 90],
  },
  WAIT: 500,
}

export const TASKS = {
  WRITE_CHARACTER: 'WRITE_CHARACTER',
  WRITE_HTML_NODE: 'WRITE_HTML_NODE',
  ERASE_CHARACTER: 'ERASE_CHARACTER',
  PAUSE: 'PAUSE',
}
