export const ELEMENT_TYPES = {
  TEXT: 'TEXT',
  HTML: 'HTML',
}

export const EVENTS = {
  WRITE_CHARACTERS: 'WRITE_CHARACTERS',
  WRITE_HTML: 'WRITE_HTML',
  ERASE_LAST_CHARACTER: 'ERASE_LAST_CHARACTER',
  ERASE_CHARACTER: 'ERASE_CHARACTER',
  WAIT: 'WAIT',
}

export const DEFAULTS = {
  CADENCE: {
    WRITE_CHARACTERS: [40, 80],
    ERASE_CHARACTER: [60, 90],
  },
}
